name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run tests
      run: |
        xcodebuild -workspace MyDay.xcworkspace -scheme MyDay -sdk iphonesimulator -destination 'platform=iOS Simulator,id=4A75EA12-FD8F-4936-9E1F-610A2C871BD5,OS=12.4,name=iPhone X' test
